export const TeamA = [
  { name: "Real Madrid", logo: "https://media.api-sports.io/football/teams/541.png" },
  { name: "Barcelona", logo: "https://media.api-sports.io/football/teams/529.png" },
  { name: "Atletico Madrid", logo: "https://media.api-sports.io/football/teams/530.png" },
  { name: "Manchester United", logo: "https://media.api-sports.io/football/teams/33.png" },
  { name: "Manchester City", logo: "https://media.api-sports.io/football/teams/50.png" },
  { name: "Liverpool", logo: "https://media.api-sports.io/football/teams/40.png" },
  { name: "Arsenal", logo: "https://media.api-sports.io/football/teams/42.png" },
  { name: "Chelsea", logo: "https://media.api-sports.io/football/teams/49.png" },
  { name: "Tottenham", logo: "https://media.api-sports.io/football/teams/47.png" },
  { name: "Newcastle", logo: "https://media.api-sports.io/football/teams/34.png" },
  { name: "PSG", logo: "https://media.api-sports.io/football/teams/85.png" },
  { name: "Marseille", logo: "https://media.api-sports.io/football/teams/81.png" },
  { name: "Lyon", logo: "https://media.api-sports.io/football/teams/80.png" },
  { name: "Monaco", logo: "https://media.api-sports.io/football/teams/91.png" },
  { name: "Bayern Munich", logo: "https://media.api-sports.io/football/teams/157.png" },
  { name: "Borussia Dortmund", logo: "https://media.api-sports.io/football/teams/165.png" },
  { name: "RB Leipzig", logo: "https://media.api-sports.io/football/teams/173.png" },
  { name: "Bayer Leverkusen", logo: "https://media.api-sports.io/football/teams/168.png" },
  { name: "Juventus", logo: "https://media.api-sports.io/football/teams/496.png" },
  { name: "Inter Milan", logo: "https://media.api-sports.io/football/teams/505.png" },
  { name: "AC Milan", logo: "https://media.api-sports.io/football/teams/489.png" },
  { name: "Napoli", logo: "https://media.api-sports.io/football/teams/492.png" },
  { name: "Roma", logo: "https://media.api-sports.io/football/teams/497.png" },
  { name: "Lazio", logo: "https://media.api-sports.io/football/teams/487.png" },
  { name: "Ajax", logo: "https://media.api-sports.io/football/teams/194.png" },
  { name: "PSV Eindhoven", logo: "https://media.api-sports.io/football/teams/197.png" },
  { name: "Feyenoord", logo: "https://media.api-sports.io/football/teams/1978.png" },
  { name: "Benfica", logo: "https://media.api-sports.io/football/teams/211.png" },
  { name: "Porto", logo: "https://media.api-sports.io/football/teams/212.png" },
  { name: "Sporting CP", logo: "https://media.api-sports.io/football/teams/228.png" },
  { name: "Celtic", logo: "https://media.api-sports.io/football/teams/247.png" },

];



export const TeamB = [


    { name: "Sevilla", logo: "https://media.api-sports.io/football/teams/536.png" },
    { name: "Real Sociedad", logo: "https://media.api-sports.io/football/teams/548.png" },
    { name: "Villarreal", logo: "https://media.api-sports.io/football/teams/533.png" },
    { name: "Real Betis", logo: "https://media.api-sports.io/football/teams/543.png" },
    { name: "Valencia", logo: "https://media.api-sports.io/football/teams/532.png" },
    { name: "Athletic Bilbao", logo: "https://media.api-sports.io/football/teams/531.png" },
    { name: "Brighton", logo: "https://media.api-sports.io/football/teams/51.png" },
    { name: "Aston Villa", logo: "https://media.api-sports.io/football/teams/66.png" },
    { name: "West Ham United", logo: "https://media.api-sports.io/football/teams/48.png" },
    { name: "Everton", logo: "https://media.api-sports.io/football/teams/45.png" },
    { name: "Leicester City", logo: "https://media.api-sports.io/football/teams/46.png" },
    { name: "Wolverhampton", logo: "https://media.api-sports.io/football/teams/39.png" },
    { name: "Nottingham Forest", logo: "https://media.api-sports.io/football/teams/65.png" },
    { name: "Eintracht Frankfurt", logo: "https://media.api-sports.io/football/teams/169.png" },
    { name: "VfB Stuttgart", logo: "https://media.api-sports.io/football/teams/172.png" },
    { name: "Werder Bremen", logo: "https://media.api-sports.io/football/teams/162.png" },
    { name: "Atalanta", logo: "https://media.api-sports.io/football/teams/499.png" },
    { name: "Fiorentina", logo: "https://media.api-sports.io/football/teams/502.png" },
    { name: "Torino", logo: "https://media.api-sports.io/football/teams/503.png" },
    { name: "Bologna", logo: "https://media.api-sports.io/football/teams/500.png" },
    { name: "Rangers", logo: "https://media.api-sports.io/football/teams/257.png" },
    { name: "Galatasaray", logo: "https://media.api-sports.io/football/teams/645.png" },
    { name: "Fenerbahce", logo: "https://media.api-sports.io/football/teams/611.png" },
    { name: "Besiktas", logo: "https://media.api-sports.io/football/teams/549.png" },
    { name: "Club Brugge", logo: "https://media.api-sports.io/football/teams/2617.png" },
    { name: "Anderlecht", logo: "https://media.api-sports.io/football/teams/2619.png" },
    { name: "Red Bull Salzburg", logo: "https://media.api-sports.io/football/teams/595.png" },
    { name: "Shakhtar Donetsk", logo: "https://media.api-sports.io/football/teams/596.png" },
    { name: "Dynamo Kyiv", logo: "https://media.api-sports.io/football/teams/597.png" },
    { name: "Olympiacos", logo: "https://media.api-sports.io/football/teams/553.png" },
    { name: "Panathinaikos", logo: "https://media.api-sports.io/football/teams/555.png" },
    { name: "Al Hilal", logo: "https://media.api-sports.io/football/teams/2939.png" },
    { name: "Al Nassr", logo: "https://media.api-sports.io/football/teams/2937.png" },
    { name: "Al Ittihad", logo: "https://media.api-sports.io/football/teams/2940.png" },
    { name: "Al Ahli", logo: "https://media.api-sports.io/football/teams/2938.png" },
    { name: "Inter Miami", logo: "https://media.api-sports.io/football/teams/9568.png" },
    { name: "LA Galaxy", logo: "https://media.api-sports.io/football/teams/1609.png" },
    { name: "Boca Juniors", logo: "https://media.api-sports.io/football/teams/435.png" },
    { name: "River Plate", logo: "https://media.api-sports.io/football/teams/436.png" },




]